### ISSUE TITLE
application.yml 파일 빼기

### ISSUE THREAD

**Issue by diast3r** [diast3r/kcalculator#3]
`.gitignore`에 추가했어야 하는 것을 깜빡했다.

- [x] DB 계정 비밀번호 바꾸기

**Comment by diast3r** [comment]
application.yml 파일은 냅두고
db 정보만 따로 넣어둔 application-db.yml 파일을 gitignore에 추가하기

```yml
# application.yml
spring:
  profiles:
    include: db
```

```yml
# application-db.yml
spring:
  datasource:
    url: (db 경로)
    username: (username)
    password: (password)
```
